In [2]:
import numpy as np

Create a 2D NumPy array of shape (3, 4) with values from 0 to 11.

In [16]:
a=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Reshape it into (4, 3) and (6, 2)

In [17]:
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,0,1]])
print(b)
c=b.reshape(6,2)
print(c)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]]


Perform element-wise multiplication with another array of the same shape.

In [18]:
a=np.array([[3,4,5],[5,6,7],[7,8,9]])
b=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(a)
print(b)
print(a*b)

[[3 4 5]
 [5 6 7]
 [7 8 9]]
[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[ 3  8 15]
 [15 24 35]
 [35 48 63]]


Slice the first two rows and last two columns.

In [27]:
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,0,1],[2,3,4,5],[5,6,7,8],[1,2,3,4]])
print(b)
print(b[2:6,0:2])

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]
 [2 3 4 5]
 [5 6 7 8]
 [1 2 3 4]]
[[8 9]
 [2 3]
 [5 6]
 [1 2]]
